apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdewv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdewv
  template:
    metadata:
      labels:
        app: asdewv
    spec:
      containers:
      - image: okteto.dev/asdewv:latest
        name: asdewv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/L-html.zip"
        - name: Vless_UUID
          value: "05ca78de-e544-4cdd-a9a9-09ffe0cb5ecc"
        - name: Vless_Path
          value: "/05ca78de-e544-4cdd-a9a9-09ffe0cb5ecc-vless"
        - name: Vmess_UUID
          value: "05ca78de-e544-4cdd-a9a9-09ffe0cb5ecc"
        - name: Vmess_Path
          value: "/05ca78de-e544-4cdd-a9a9-09ffe0cb5ecc-vmess"
        - name: Share_Path
          value: "/v2yyhgff"
